/* Gängige unregelmäßige Verben (Klasse 5–8). Generisches Sprachwissen,
   bewusst KEINE Green-Line-Inhalte. Varianten mit "/" gelten beide. */

export interface Verb {
  infinitive: string
  past: string
  participle: string
  german: string
}

export const VERBS: Verb[] = [
  { infinitive: 'be', past: 'was/were', participle: 'been', german: 'sein' },
  { infinitive: 'become', past: 'became', participle: 'become', german: 'werden' },
  { infinitive: 'begin', past: 'began', participle: 'begun', german: 'beginnen' },
  { infinitive: 'bite', past: 'bit', participle: 'bitten', german: 'beißen' },
  { infinitive: 'blow', past: 'blew', participle: 'blown', german: 'blasen; wehen' },
  { infinitive: 'break', past: 'broke', participle: 'broken', german: 'brechen' },
  { infinitive: 'bring', past: 'brought', participle: 'brought', german: 'bringen' },
  { infinitive: 'build', past: 'built', participle: 'built', german: 'bauen' },
  { infinitive: 'buy', past: 'bought', participle: 'bought', german: 'kaufen' },
  { infinitive: 'catch', past: 'caught', participle: 'caught', german: 'fangen' },
  { infinitive: 'choose', past: 'chose', participle: 'chosen', german: 'wählen' },
  { infinitive: 'come', past: 'came', participle: 'come', german: 'kommen' },
  { infinitive: 'cost', past: 'cost', participle: 'cost', german: 'kosten' },
  { infinitive: 'cut', past: 'cut', participle: 'cut', german: 'schneiden' },
  { infinitive: 'do', past: 'did', participle: 'done', german: 'tun; machen' },
  { infinitive: 'draw', past: 'drew', participle: 'drawn', german: 'zeichnen; ziehen' },
  { infinitive: 'dream', past: 'dreamt/dreamed', participle: 'dreamt/dreamed', german: 'träumen' },
  { infinitive: 'drink', past: 'drank', participle: 'drunk', german: 'trinken' },
  { infinitive: 'drive', past: 'drove', participle: 'driven', german: 'fahren' },
  { infinitive: 'eat', past: 'ate', participle: 'eaten', german: 'essen' },
  { infinitive: 'fall', past: 'fell', participle: 'fallen', german: 'fallen' },
  { infinitive: 'feed', past: 'fed', participle: 'fed', german: 'füttern' },
  { infinitive: 'feel', past: 'felt', participle: 'felt', german: 'fühlen' },
  { infinitive: 'fight', past: 'fought', participle: 'fought', german: 'kämpfen' },
  { infinitive: 'find', past: 'found', participle: 'found', german: 'finden' },
  { infinitive: 'fly', past: 'flew', participle: 'flown', german: 'fliegen' },
  { infinitive: 'forget', past: 'forgot', participle: 'forgotten', german: 'vergessen' },
  { infinitive: 'forgive', past: 'forgave', participle: 'forgiven', german: 'verzeihen' },
  { infinitive: 'freeze', past: 'froze', participle: 'frozen', german: 'frieren' },
  { infinitive: 'get', past: 'got', participle: 'got/gotten', german: 'bekommen' },
  { infinitive: 'give', past: 'gave', participle: 'given', german: 'geben' },
  { infinitive: 'go', past: 'went', participle: 'gone', german: 'gehen' },
  { infinitive: 'grow', past: 'grew', participle: 'grown', german: 'wachsen' },
  { infinitive: 'hang', past: 'hung', participle: 'hung', german: 'hängen' },
  { infinitive: 'have', past: 'had', participle: 'had', german: 'haben' },
  { infinitive: 'hear', past: 'heard', participle: 'heard', german: 'hören' },
  { infinitive: 'hide', past: 'hid', participle: 'hidden', german: 'verstecken' },
  { infinitive: 'hit', past: 'hit', participle: 'hit', german: 'schlagen; treffen' },
  { infinitive: 'hold', past: 'held', participle: 'held', german: 'halten' },
  { infinitive: 'hurt', past: 'hurt', participle: 'hurt', german: 'wehtun; verletzen' },
  { infinitive: 'keep', past: 'kept', participle: 'kept', german: 'behalten' },
  { infinitive: 'know', past: 'knew', participle: 'known', german: 'wissen; kennen' },
  { infinitive: 'learn', past: 'learnt/learned', participle: 'learnt/learned', german: 'lernen' },
  { infinitive: 'leave', past: 'left', participle: 'left', german: 'verlassen; abfahren' },
  { infinitive: 'lend', past: 'lent', participle: 'lent', german: 'leihen' },
  { infinitive: 'let', past: 'let', participle: 'let', german: 'lassen' },
  { infinitive: 'lose', past: 'lost', participle: 'lost', german: 'verlieren' },
  { infinitive: 'make', past: 'made', participle: 'made', german: 'machen' },
  { infinitive: 'mean', past: 'meant', participle: 'meant', german: 'bedeuten; meinen' },
  { infinitive: 'meet', past: 'met', participle: 'met', german: 'treffen' },
  { infinitive: 'pay', past: 'paid', participle: 'paid', german: 'bezahlen' },
  { infinitive: 'put', past: 'put', participle: 'put', german: 'legen; stellen' },
  { infinitive: 'read', past: 'read', participle: 'read', german: 'lesen' },
  { infinitive: 'ride', past: 'rode', participle: 'ridden', german: 'reiten; fahren' },
  { infinitive: 'ring', past: 'rang', participle: 'rung', german: 'klingeln' },
  { infinitive: 'rise', past: 'rose', participle: 'risen', german: 'aufgehen; steigen' },
  { infinitive: 'run', past: 'ran', participle: 'run', german: 'laufen; rennen' },
  { infinitive: 'say', past: 'said', participle: 'said', german: 'sagen' },
  { infinitive: 'see', past: 'saw', participle: 'seen', german: 'sehen' },
  { infinitive: 'sell', past: 'sold', participle: 'sold', german: 'verkaufen' },
  { infinitive: 'send', past: 'sent', participle: 'sent', german: 'schicken' },
  { infinitive: 'shine', past: 'shone', participle: 'shone', german: 'scheinen' },
  { infinitive: 'show', past: 'showed', participle: 'shown', german: 'zeigen' },
  { infinitive: 'shut', past: 'shut', participle: 'shut', german: 'schließen' },
  { infinitive: 'sing', past: 'sang', participle: 'sung', german: 'singen' },
  { infinitive: 'sit', past: 'sat', participle: 'sat', german: 'sitzen' },
  { infinitive: 'sleep', past: 'slept', participle: 'slept', german: 'schlafen' },
  { infinitive: 'speak', past: 'spoke', participle: 'spoken', german: 'sprechen' },
  { infinitive: 'spend', past: 'spent', participle: 'spent', german: 'ausgeben; verbringen' },
  { infinitive: 'stand', past: 'stood', participle: 'stood', german: 'stehen' },
  { infinitive: 'steal', past: 'stole', participle: 'stolen', german: 'stehlen' },
  { infinitive: 'swim', past: 'swam', participle: 'swum', german: 'schwimmen' },
  { infinitive: 'take', past: 'took', participle: 'taken', german: 'nehmen' },
  { infinitive: 'teach', past: 'taught', participle: 'taught', german: 'unterrichten' },
  { infinitive: 'tell', past: 'told', participle: 'told', german: 'erzählen' },
  { infinitive: 'think', past: 'thought', participle: 'thought', german: 'denken' },
  { infinitive: 'throw', past: 'threw', participle: 'thrown', german: 'werfen' },
  { infinitive: 'understand', past: 'understood', participle: 'understood', german: 'verstehen' },
  { infinitive: 'wake', past: 'woke', participle: 'woken', german: 'aufwachen' },
  { infinitive: 'wear', past: 'wore', participle: 'worn', german: 'tragen (Kleidung)' },
  { infinitive: 'win', past: 'won', participle: 'won', german: 'gewinnen' },
  { infinitive: 'write', past: 'wrote', participle: 'written', german: 'schreiben' },
]
